image: python:3.8

services:
  - postgres:9.6

variables:
  POSTGRES_DB: sodar
  POSTGRES_USER: sodar
  POSTGRES_PASSWORD: sodar
  DATABASE_URL: postgres://sodar:sodar@postgres/sodar
  DEBIAN_FRONTEND: noninteractive

before_script:
  # SSH setup taken from https://gitlab.com/gitlab-examples/ssh-private-key
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  - sh ./utility/install_os_gitlab.sh
  - sh ./utility/install_chrome_gitlab.sh
  - pip3 install virtualenv
  - virtualenv env
  - source env/bin/activate
  - sh ./utility/install_python_dependencies.sh
  - npm ci --prefix samplesheets/vueapp
  # Temporary HACK, should not actually do this
  - nohup npm run -prefix samplesheets/vueapp serve &

all_tests:
  script:
    - python3 manage.py collectstatic --noinput
    - coverage run --source="." manage.py test -v 2 --settings=config.settings.test
    - coverage report
    - make black arg=--check
    - flake8 .
    - make test_samplesheets_vue
  when: on_success
