from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<project>\d+)$',
        view=views.ProjectFileView.as_view(),
        name='project_files',
    ),
    url(
        regex=r'^(?P<project>\d+)/folder/(?P<folder>\d+)$',
        view=views.ProjectFileView.as_view(),
        name='project_files',
    ),
    url(
        regex=r'^(?P<project>\d+)/upload$',
        view=views.FileCreateView.as_view(),
        name='file_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/folder/(?P<folder>\d+)/upload$',
        view=views.FileCreateView.as_view(),
        name='file_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/update_file/(?P<pk>\d+)$',
        view=views.FileUpdateView.as_view(),
        name='file_update',
    ),
    url(
        regex=r'^(?P<project>\d+)/delete_file/(?P<pk>\d+)$',
        view=views.FileDeleteView.as_view(),
        name='file_delete',
    ),
    url(
        regex=r'^(?P<project>\d+)/download/'
              r'(?P<pk>\d+)/(?P<file_name>[^\0]{0,256})$',
        view=views.FileServeView.as_view(),
        name='file_serve',
    ),
    url(
        regex=r'^download/(?P<secret>[\w\-]+)/(?P<file_name>[^\0]{0,256})$',
        view=views.FileServePublicView.as_view(),
        name='file_serve_public',
    ),
    url(
        regex=r'^(?P<project>\d+)/link/(?P<pk>\d+)$',
        view=views.FilePublicLinkView.as_view(),
        name='file_public_link',
    ),
    url(
        regex=r'^(?P<project>\d+)/add_folder$',
        view=views.FolderCreateView.as_view(),
        name='folder_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/folder/(?P<folder>\d+)/add_folder$',
        view=views.FolderCreateView.as_view(),
        name='folder_create',
    ),
    url(
        regex=r'^update_folder/(?P<pk>\d+)$',
        view=views.FolderUpdateView.as_view(),
        name='folder_update',
    ),
    url(
        regex=r'^delete_folder/(?P<pk>\d+)$',
        view=views.FolderDeleteView.as_view(),
        name='folder_delete',
    ),
    url(
        regex=r'^(?P<project>\d+)/add_link$',
        view=views.HyperLinkCreateView.as_view(),
        name='hyperlink_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/folder/(?P<folder>\d+)/add_link$',
        view=views.HyperLinkCreateView.as_view(),
        name='hyperlink_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/update_link/(?P<pk>\d+)$',
        view=views.HyperLinkUpdateView.as_view(),
        name='hyperlink_update',
    ),
    url(
        regex=r'^(?P<project>\d+)/delete_link/(?P<pk>\d+)$',
        view=views.HyperLinkDeleteView.as_view(),
        name='hyperlink_delete',
    ),
    url(
        regex=r'^(?P<project>\d+)/batch_edit$',
        view=views.BatchEditView.as_view(),
        name='batch_edit',
    ),
    url(
        regex=r'^(?P<project>\d+)/folder/(?P<folder>\d+)/batch_edit$',
        view=views.BatchEditView.as_view(),
        name='batch_edit',
    ),
]
