# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181023_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='omics_uuid',
            new_name='sodar_uuid'
        ),
    ]
