# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 10:08
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sodar_uuid',
            field=models.UUIDField(
                default=uuid.uuid4, help_text='User SODAR UUID', unique=True
            ),
        ),
    ]
