# Generated by Django 5.2.8 on 2025-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_update_first_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_update',
            field=models.BooleanField(
                default=True,
                help_text='Enable user profile updating for local user.',
            ),
        ),
    ]
