# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projectroles', '0002_populate_roles')]

    # To be squashed..
