# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:14
from __future__ import unicode_literals

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0004_projectusertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Project Omics UUID', null=True),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='ProjectInvite Omics UUID', null=True),
        ),
        migrations.AddField(
            model_name='projectsetting',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='ProjectSetting Omics UUID', null=True),
        ),
        migrations.AddField(
            model_name='projectusertag',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='ProjectUserTag Omics UUID', null=True),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='RoleAssignment Omics UUID', null=True),
        ),
    ]
