# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:17
from __future__ import unicode_literals

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    models = [
        'Project',
        'ProjectInvite',
        'ProjectSetting',
        'ProjectUserTag',
        'RoleAssignment']

    for m in models:
        my_model = apps.get_model('projectroles', m)

        for row in my_model.objects.all():
            row.omics_uuid = uuid.uuid4()
            row.save(update_fields=['omics_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0005_add_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
