# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0006_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   help_text='Project Omics UUID', unique=True),
        ),
        migrations.AlterField(
            model_name='projectinvite',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   help_text='ProjectInvite Omics UUID',
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='projectsetting',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   help_text='ProjectSetting Omics UUID',
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='projectusertag',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   help_text='ProjectUserTag Omics UUID',
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='omics_uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   help_text='RoleAssignment Omics UUID',
                                   unique=True),
        ),
    ]
