# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0007_remove_uuid_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['project'], name='projectrole_project_b13795_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user'], name='projectrole_user_id_0e46f7_idx'),
        ),
    ]
