# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0008_auto_20180322_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category if nested', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projectroles.Project'),
        ),
    ]
