from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<pk>\d+)$',
        view=views.ProjectDetailView.as_view(),
        name='project_detail',
    ),
    url(
        regex=r'^(?P<pk>\d+)/update$',
        view=views.ProjectUpdateView.as_view(),
        name='project_update',
    ),
    url(
        regex=r'^create$',
        view=views.ProjectCreateView.as_view(),
        name='project_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/create$',
        view=views.ProjectCreateView.as_view(),
        name='project_create',
    ),
    url(
        regex=r'^search$',
        view=views.ProjectSearchView.as_view(),
        name='project_search',
    ),
    url(
        regex=r'^(?P<pk>\d+)/roles$',
        view=views.ProjectRoleView.as_view(),
        name='project_roles',
    ),
    url(
        regex=r'^(?P<project>\d+)/roles/create$',
        view=views.RoleAssignmentCreateView.as_view(),
        name='role_create',
    ),
    url(
        regex=r'^(?P<project>\d+)/roles/(?P<pk>\d+)/update$',
        view=views.RoleAssignmentUpdateView.as_view(),
        name='role_update',
    ),
    url(
        regex=r'^(?P<project>\d+)/roles/(?P<pk>\d+)/delete$',
        view=views.RoleAssignmentDeleteView.as_view(),
        name='role_delete',
    ),
    url(
        regex=r'^(?P<project>\d+)/invites$',
        view=views.ProjectInviteView.as_view(),
        name='role_invites',
    ),
    url(
        regex=r'^(?P<project>\d+)/create_invite$',
        view=views.ProjectInviteCreateView.as_view(),
        name='role_invite_create',
    ),
    url(
        regex=r'^invite/(?P<secret>[\w\-]+)$',
        view=views.ProjectInviteAcceptView.as_view(),
        name='role_invite_accept',
    ),
    url(
        regex=r'^(?P<project>\d+)/invites/(?P<pk>\d+)/resend$',
        view=views.ProjectInviteResendView.as_view(),
        name='role_invite_resend',
    ),
    url(
        regex=r'^(?P<project>\d+)/invites/(?P<pk>\d+)/revoke$',
        view=views.ProjectInviteRevokeView.as_view(),
        name='role_invite_revoke',
    ),
    url(
        regex=r'^(?P<project>\d+)/settings$',
        view=views.ProjectSettingUpdateView.as_view(),
        name='settings_update',
    ),
    # Javascript API Views
    url(
        regex=r'^(?P<pk>\d+)/star',
        view=views.ProjectStarringAPIView.as_view(),
        name='project_star',
    ),
    # Taskflow API Views
    url(
        regex=r'^taskflow/project/get$',
        view=views.ProjectGetAPIView.as_view(),
        name='taskflow_project_get',
    ),
    url(
        regex=r'^taskflow/project/update$',
        view=views.ProjectUpdateAPIView.as_view(),
        name='taskflow_project_update',
    ),
    url(
        regex=r'^taskflow/role/get$',
        view=views.RoleAssignmentGetAPIView.as_view(),
        name='taskflow_role_get',
    ),
    url(
        regex=r'^taskflow/role/set$',
        view=views.RoleAssignmentSetAPIView.as_view(),
        name='taskflow_role_set',
    ),
    url(
        regex=r'^taskflow/role/delete$',
        view=views.RoleAssignmentDeleteAPIView.as_view(),
        name='taskflow_role_delete',
    ),
    url(
        regex=r'^irods-info',
        view=views.IrodsInfoView.as_view(),
        name='irods_info',
    ),
]
