# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectroles', '0003_populate_roles'),
        ('samplesheets', '0002_investigation_irods_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the landing zone', max_length=255)),
                ('status', models.CharField(default='ACTIVE', help_text='Status of landing zone', max_length=64)),
                ('status_info', models.CharField(blank=True, default='Available with write access for user', help_text='Additional status information', max_length=1024, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last landing zone modification')),
                ('description', models.TextField(blank=True, help_text='Landing zone description (optional)')),
                ('omics_uuid', models.UUIDField(default=uuid.uuid4, help_text='Landing zone Omics UUID', unique=True)),
                ('assay', models.ForeignKey(help_text='Assay for which the landing zone belongs', on_delete=django.db.models.deletion.CASCADE, related_name='landing_zones', to='samplesheets.Assay')),
                ('project', models.ForeignKey(help_text='Project in which the landing zone belongs', on_delete=django.db.models.deletion.CASCADE, related_name='landing_zones', to='projectroles.Project')),
                ('user', models.ForeignKey(help_text='User who owns the landing zone', on_delete=django.db.models.deletion.CASCADE, related_name='landing_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='landingzone',
            unique_together=set([('title', 'project', 'user')]),
        ),
    ]
