# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingzones', '0002_auto_20180503_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingzone',
            options={'ordering': ['project', 'assay__file_name', 'title']},
        ),
    ]
