# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 09:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingzones', '0003_auto_20180530_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingzone',
            name='config_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Configuration data (for storing plugin-specific settings)'),
        ),
        migrations.AddField(
            model_name='landingzone',
            name='configuration',
            field=models.CharField(blank=True, help_text='Special configuration (optional, leave blank for a standard landing zone)', max_length=64, null=True),
        ),
    ]
