# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landingzones', '0004_auto_20180628_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingzone',
            old_name='omics_uuid',
            new_name='sodar_uuid'
        ),
    ]
