# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 11:00
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingzones', '0005_rename_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingzone',
            name='sodar_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Landing zone SODAR UUID', unique=True),
        ),
    ]
