# Generated by Django 3.2.4 on 2021-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingzones', '0006_update_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingzone',
            name='config_data',
            field=models.JSONField(default=dict, help_text='Configuration data (for storing plugin-specific settings)'),
        ),
    ]
