# Generated by Django 3.2.6 on 2021-08-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingzones', '0007_update_jsonfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingzone',
            name='user_message',
            field=models.CharField(blank=True, help_text='Message displayed to project members on successful zone moving if member notifications are enabled (optional)', max_length=1024),
        ),
    ]
