# Generated by Django 4.2.25 on 2025-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('landingzones', '0009_alter_landingzone_status_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingzone',
            name='coll_creation',
            field=models.CharField(
                default='ZONE_COLLS_NONE',
                help_text='Create landing zone subcollections',
            ),
        ),
    ]
