# Generated by Django 4.2.25 on 2025-10-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('landingzones', '0010_landingzone_coll_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingzone',
            name='coll_creation',
            field=models.CharField(
                default='NONE', help_text='Create landing zone subcollections'
            ),
        ),
    ]
