# Generated by Django 4.2.26 on 2025-11-20 08:56

from django.db import migrations

OLD_VAL = 'ZONE_COLLS_NONE'
NEW_VAL = 'NONE'


def update_coll_creation_values(apps, schema_editor):
    """
    Update default coll_creation values of existing LandingZones objects
    """
    LandingZone = apps.get_model('landingzones', 'LandingZone')
    for zone in LandingZone.objects.filter(coll_creation=OLD_VAL):
        zone.coll_creation = NEW_VAL
        zone.save()


class Migration(migrations.Migration):
    dependencies = [
        ('landingzones', '0011_alter_landingzone_coll_creation'),
    ]

    operations = [
        migrations.RunPython(
            code=update_coll_creation_values,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
