# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 14:45
from __future__ import unicode_literals

from django.conf import settings
from omics_data_mgmt.users.models import User
# from django.contrib.users.models import User
from django.db import migrations


def create_user(apps, schema_editor):
    User.objects.create_user(
        username=settings.LZ_BIH_PROTEOMICS_SMB_USER,
        password=settings.LZ_BIH_PROTEOMICS_SMB_PASS)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_user)
    ]
