# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminalerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminalert',
            name='active',
            field=models.BooleanField(default=True, help_text='Alert status (for disabling the alert before expiration)'),
        ),
    ]
