# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesfolders', '0002_auto_20171017_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='flag',
            field=models.CharField(blank=True, help_text='Flag (optional)', max_length=64),
        ),
        migrations.AddField(
            model_name='folder',
            name='flag',
            field=models.CharField(blank=True, help_text='Flag (optional)', max_length=64),
        ),
        migrations.AddField(
            model_name='hyperlink',
            name='flag',
            field=models.CharField(blank=True, help_text='Flag (optional)', max_length=64),
        ),
    ]
