# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyaccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oboformatontology',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='oboformatontology',
            name='file',
            field=models.CharField(blank=True, help_text='Ontology file name or URL', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='oboformatontology',
            name='name',
            field=models.CharField(default='ONTOLOGY', help_text='Ontology name as it appears in sample sheets', max_length=255, unique=True),
        ),
    ]
