# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyaccess', '0002_add_name_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oboformatontologyterm',
            name='name',
            field=models.CharField(help_text='Term name', max_length=1024),
        ),
    ]
