# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='irods_status',
            field=models.BooleanField(default=False, help_text='Status of iRODS directory structure creation'),
        ),
    ]
