# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='previous_process',
            field=models.OneToOneField(help_text='Previous process (can be None for first process in sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_process', to='samplesheets.Process'),
        ),
    ]
