# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 14:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmaterial',
            name='factor_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Factor values for a sample', null=True),
        ),
    ]
