# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmaterial',
            name='extract_label',
            field=models.CharField(blank=True, help_text='Extract label', max_length=255, null=True),
        ),
    ]
