# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='file_name',
            field=models.CharField(help_text='File name for exporting', max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='file_name',
            field=models.CharField(help_text='File name for exporting', max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='identifier',
            field=models.CharField(help_text='Locally unique identifier', max_length=255),
        ),
    ]
