# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='json_id',
        ),
        migrations.RemoveField(
            model_name='genericmaterial',
            name='json_id',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='json_id',
        ),
        migrations.RemoveField(
            model_name='process',
            name='json_id',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='json_id',
        ),
        migrations.RemoveField(
            model_name='study',
            name='json_id',
        ),
        migrations.AddField(
            model_name='assay',
            name='api_id',
            field=models.CharField(blank=True, help_text='ISA API object id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericmaterial',
            name='api_id',
            field=models.CharField(blank=True, help_text='ISA API object id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='api_id',
            field=models.CharField(blank=True, help_text='ISA API object id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='api_id',
            field=models.CharField(blank=True, help_text='ISA API object id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='api_id',
            field=models.CharField(blank=True, help_text='ISA API object id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='api_id',
            field=models.CharField(blank=True, help_text='ISA API object id', max_length=255, null=True),
        ),
    ]
