# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0002_investigation_irods_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assay',
            options={'ordering': ['study__file_name', 'file_name']},
        ),
        migrations.AddField(
            model_name='investigation',
            name='active',
            field=models.BooleanField(default=False, help_text='Active status of investigation (one active per project)'),
        ),
    ]
