# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 14:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0002_auto_20180205_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmaterial',
            name='factor_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='Factor values for a sample'),
        ),
    ]
