# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0002_genericmaterial_extract_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='assay',
            field=models.ForeignKey(help_text='Assay to which the arc belongs (for assay sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arcs_old', to='samplesheets.Assay'),
        ),
        migrations.AlterField(
            model_name='arc',
            name='study',
            field=models.ForeignKey(help_text='Study to which the arc belongs (for study sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arcs_old', to='samplesheets.Study'),
        ),
    ]
