# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0002_auto_20180212_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='identifier',
            field=models.CharField(help_text='Locally unique identifier', max_length=255),
        ),
    ]
