# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 16:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0002_auto_20180215_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericmaterial',
            options={'ordering': ['name'], 'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['identifier'], 'verbose_name_plural': 'studies'},
        ),
        migrations.AddField(
            model_name='assay',
            name='header',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Column headers'),
        ),
        migrations.AddField(
            model_name='study',
            name='header',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Column headers'),
        ),
    ]
