# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 11:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

from samplesheets.utils import get_alt_names


def populate_alt_names(apps, schema_editor):
    GenericMaterial = apps.get_model('samplesheets', 'GenericMaterial')

    for m in GenericMaterial.objects.all():
        if not m.alt_names:
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0003_auto_20180530_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmaterial',
            name='alt_names',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True, max_length=255), size=None),
                default=list, help_text='Alternative names', size=None),
        ),
        migrations.RunPython(populate_alt_names),
    ]
