# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 15:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0003_auto_20180315_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='arcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, help_text='Assay arcs', size=None),
        ),
        migrations.AddField(
            model_name='study',
            name='arcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, help_text='Study arcs', size=None),
        ),
    ]
