# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0003_auto_20180226_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='process',
            name='next_process',
        ),
        migrations.RemoveField(
            model_name='process',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='process',
            name='previous_process',
        ),
    ]
