# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0003_auto_20180213_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='file_name',
            field=models.CharField(help_text='File name for exporting', max_length=255),
        ),
    ]
