# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0004_auto_20180207_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='assay',
            field=models.ForeignKey(help_text='Assay to which the process belongs (for assay sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='samplesheets.Assay'),
        ),
        migrations.AddField(
            model_name='process',
            name='study',
            field=models.ForeignKey(help_text='Study to which the process belongs (for study sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='samplesheets.Study'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='first_process',
            field=models.ForeignKey(help_text='First process in the process sequence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assay_of_first_process', to='samplesheets.Process'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='assay',
            field=models.ForeignKey(help_text='Assay to which the material belongs (for assay sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='samplesheets.Assay'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='study',
            field=models.ForeignKey(help_text='Study to which the material belongs (for study sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='samplesheets.Study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='first_process',
            field=models.ForeignKey(help_text='First process in the process sequence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_of_first_process', to='samplesheets.Process'),
        ),
    ]
