# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 16:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0004_auto_20180315_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='assay',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='head_material',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='head_process',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='study',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='tail_material',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='tail_process',
        ),
        migrations.AlterField(
            model_name='assay',
            name='arcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None), default=list, help_text='Assay arcs', size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='arcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None), default=list, help_text='Study arcs', size=None),
        ),
        migrations.DeleteModel(
            name='Arc',
        ),
    ]
