# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('samplesheets', '0004_auto_20180227_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_object_id', models.PositiveIntegerField()),
                ('head_object_id', models.PositiveIntegerField()),
                ('assay', models.ForeignKey(help_text='Assay to which the arc belongs (for assay sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='samplesheets.Assay')),
                ('head_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplesheets_arc_as_head', to='contenttypes.ContentType')),
                ('study', models.ForeignKey(help_text='Study to which the arc belongs (for study sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='samplesheets.Study')),
                ('tail_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplesheets_arc_as_tail', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('study', 'assay', 'tail_object__name', 'head_object__name'),
            },
        ),
    ]
