# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 10:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0004_auto_20180213_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='protocol_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Protocol type', null=True),
        ),
    ]
