# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0005_auto_20180208_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='first_process',
        ),
        migrations.RemoveField(
            model_name='study',
            name='first_process',
        ),
    ]
