# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0005_auto_20180315_1737'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genericmaterial',
            name='samplesheet_name_b020c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='genericmaterial',
            name='samplesheet_study_i_408748_idx',
        ),
        migrations.AddIndex(
            model_name='genericmaterial',
            index=models.Index(fields=['study'], name='samplesheet_study_i_cc3e33_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['unique_name'], name='samplesheet_unique__a529d5_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['study'], name='samplesheet_study_i_ca59b5_idx'),
        ),
    ]
