# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0005_auto_20180214_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='next_process',
            field=models.OneToOneField(help_text='Next process (can be None for the last process in sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_from_next', to='samplesheets.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='previous_process',
            field=models.OneToOneField(help_text='Previous process (can be None for first process in sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_from_previous', to='samplesheets.Process'),
        ),
    ]
