# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0005_arc'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='scan_name',
            field=models.CharField(blank=True, help_text='Scan name for special cases in ISAtab', max_length=255, null=True),
        ),
    ]
