# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0006_auto_20180316_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='render_table',
        ),
        migrations.RemoveField(
            model_name='study',
            name='render_table',
        ),
    ]
