# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0006_process_scan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='array_design_ref',
            field=models.CharField(blank=True, help_text='Array design ref', max_length=255, null=True),
        ),
    ]
