# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0007_process_array_design_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ('study', 'assay')},
        ),
        migrations.RemoveField(
            model_name='arc',
            name='head_content_type',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='head_object_id',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='tail_content_type',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='tail_object_id',
        ),
        migrations.AddField(
            model_name='arc',
            name='head_material',
            field=models.ForeignKey(help_text='Head material (can be null if head object is a process)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arcs_as_head', to='samplesheets.GenericMaterial'),
        ),
        migrations.AddField(
            model_name='arc',
            name='head_process',
            field=models.ForeignKey(help_text='Head process (can be null if head object is a material)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arcs_as_head', to='samplesheets.Process'),
        ),
        migrations.AddField(
            model_name='arc',
            name='tail_material',
            field=models.ForeignKey(help_text='Tail material (can be null if tail object is a process)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arcs_as_tail', to='samplesheets.GenericMaterial'),
        ),
        migrations.AddField(
            model_name='arc',
            name='tail_process',
            field=models.ForeignKey(help_text='Tail process (can be null if tail object is a material)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arcs_as_tail', to='samplesheets.Process'),
        ),
    ]
