# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0007_auto_20180316_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='status',
        ),
    ]
