# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 12:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0009_remove_genericmaterial_extract_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericmaterial',
            name='extract_label_json',
        ),
        migrations.AddField(
            model_name='genericmaterial',
            name='extract_label',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Extract label', null=True),
        ),
    ]
