# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0010_auto_20180306_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='status',
            field=models.CharField(blank=True, default='OK', help_text='Creation/editing status of investigation', max_length=64, null=True),
        ),
    ]
