# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0010_rename_extract_label'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genericmaterial',
            name='samplesheet_study_i_cc3e33_idx',
        ),
        migrations.RemoveIndex(
            model_name='process',
            name='samplesheet_study_i_ca59b5_idx',
        ),
    ]
