# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 10:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0011_investigation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='render_table',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Pre-constructed assay table for rendering'),
        ),
        migrations.AddField(
            model_name='study',
            name='render_table',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Pre-constructed study table for rendering'),
        ),
    ]
