# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 12:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0010_update_appsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samplesheets', '0012_import_export_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISATab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_uuid', models.UUIDField(blank=True, help_text='UUID of related Investigation', null=True)),
                ('archive_name', models.CharField(blank=True, help_text='File name of ISAtab archive (optional)', max_length=255, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Data from ISAtab files as a dict')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, help_text='Tags for categorizing the ISAtab', size=None)),
                ('date_created', models.DateTimeField(auto_now=True, help_text='DateTime of ISAtab creation')),
                ('parser_version', models.CharField(blank=True, help_text='Version of altamISA used when processing this ISAtab', max_length=255, null=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Optional extra data')),
                ('sodar_uuid', models.UUIDField(default=uuid.uuid4, help_text='SODAR UUID for the object', unique=True)),
                ('project', models.ForeignKey(help_text='Project to which the ISAtab belongs', on_delete=django.db.models.deletion.CASCADE, related_name='isatabs', to='projectroles.Project')),
                ('user', models.ForeignKey(help_text='User saving this ISAtab (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isatabs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
