# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0012_auto_20180307_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmaterial',
            name='unique_name',
            field=models.CharField(blank=True, help_text='Unique material name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='unique_name',
            field=models.CharField(blank=True, help_text='Unique process name', max_length=255, null=True),
        ),
    ]
