# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0013_auto_20180307_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='genericmaterial',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='process',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='study',
            name='api_id',
        ),
        migrations.AddIndex(
            model_name='arc',
            index=models.Index(fields=['study'], name='samplesheet_study_i_77f312_idx'),
        ),
        migrations.AddIndex(
            model_name='arc',
            index=models.Index(fields=['assay'], name='samplesheet_assay_i_025e79_idx'),
        ),
        migrations.AddIndex(
            model_name='genericmaterial',
            index=models.Index(fields=['name'], name='samplesheet_name_b020c4_idx'),
        ),
        migrations.AddIndex(
            model_name='genericmaterial',
            index=models.Index(fields=['unique_name'], name='samplesheet_unique__b757a5_idx'),
        ),
    ]
