# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-18 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0017_project_full_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samplesheets', '0014_irodsaccessticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrodsDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='delete', help_text='Action to be performed', max_length=64)),
                ('target_path', models.CharField(blank=True, help_text='Target path for action', max_length=512, null=True)),
                ('path', models.CharField(help_text='Full path to iRODS data object or collection', max_length=1024)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('ACCEPTED', 'accepted'), ('FAILED', 'failed')], default='ACTIVE', help_text='Status of the request', max_length=16)),
                ('status_info', models.TextField(help_text='Optional information reqarding current status')),
                ('description', models.CharField(help_text='Request description', max_length=1024)),
                ('date_created', models.DateTimeField(auto_now=True, help_text='DateTime of request creation')),
                ('sodar_uuid', models.UUIDField(default=uuid.uuid4, help_text='SODAR UUID for the object', unique=True)),
                ('project', models.ForeignKey(help_text='Project to which the iRODS delete request belongs', on_delete=django.db.models.deletion.CASCADE, related_name='irods_data_request', to='projectroles.Project')),
                ('user', models.ForeignKey(help_text='User initiating the request', on_delete=django.db.models.deletion.CASCADE, related_name='irods_data_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
