# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 10:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0014_auto_20180308_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmaterial',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='item_type',
            field=models.CharField(choices=[('SOURCE', 'Source'), ('MATERIAL', 'Material'), ('SAMPLE', 'Sample'), ('DATA', 'Data File')], default='MATERIAL', max_length=255),
        ),
    ]
