# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0015_irodsdatarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='DateTime of last modification'),
        ),
    ]
