# Generated by Django 3.2.4 on 2021-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0016_investigation_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='comments',
            field=models.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='measurement_type',
            field=models.JSONField(default=dict, help_text='Measurement type'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='retraction_data',
            field=models.JSONField(default=dict, help_text='Consent retraction data'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='sharing_data',
            field=models.JSONField(default=dict, help_text='Data sharing rules'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='technology_type',
            field=models.JSONField(default=dict, help_text='Technology type'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='characteristics',
            field=models.JSONField(default=dict, help_text='Material characteristics'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='comments',
            field=models.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='extra_material_type',
            field=models.JSONField(blank=True, default=dict, help_text='Extra material type (from "material_type")', null=True),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='extract_label',
            field=models.JSONField(blank=True, default=dict, help_text='Extract label', null=True),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='factor_values',
            field=models.JSONField(blank=True, default=list, help_text='Factor values for a sample', null=True),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='retraction_data',
            field=models.JSONField(default=dict, help_text='Consent retraction data'),
        ),
        migrations.AlterField(
            model_name='genericmaterial',
            name='sharing_data',
            field=models.JSONField(default=dict, help_text='Data sharing rules'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='comments',
            field=models.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='contacts',
            field=models.JSONField(default=dict, help_text='Investigation contacts'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='ontology_source_refs',
            field=models.JSONField(default=dict, help_text='Ontology source references'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='parser_warnings',
            field=models.JSONField(default=dict, help_text='Warnings from the previous parsing of the corresponding ISAtab'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='publications',
            field=models.JSONField(default=dict, help_text='Investigation publications'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='retraction_data',
            field=models.JSONField(default=dict, help_text='Consent retraction data'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='sharing_data',
            field=models.JSONField(default=dict, help_text='Data sharing rules'),
        ),
        migrations.AlterField(
            model_name='isatab',
            name='data',
            field=models.JSONField(default=dict, help_text='Data from ISAtab files as a dict'),
        ),
        migrations.AlterField(
            model_name='isatab',
            name='extra_data',
            field=models.JSONField(default=dict, help_text='Optional extra data'),
        ),
        migrations.AlterField(
            model_name='process',
            name='comments',
            field=models.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='process',
            name='first_dimension',
            field=models.JSONField(default=dict, help_text='First dimension (optional, for special case)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='parameter_values',
            field=models.JSONField(default=dict, help_text='Process parameter values'),
        ),
        migrations.AlterField(
            model_name='process',
            name='retraction_data',
            field=models.JSONField(default=dict, help_text='Consent retraction data'),
        ),
        migrations.AlterField(
            model_name='process',
            name='second_dimension',
            field=models.JSONField(default=dict, help_text='Second dimension (optional, for special case)'),
        ),
        migrations.AlterField(
            model_name='process',
            name='sharing_data',
            field=models.JSONField(default=dict, help_text='Data sharing rules'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='comments',
            field=models.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='components',
            field=models.JSONField(default=dict, help_text='Protocol components'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Protocol parameters'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_type',
            field=models.JSONField(default=dict, help_text='Protocol type', null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='retraction_data',
            field=models.JSONField(default=dict, help_text='Consent retraction data'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='sharing_data',
            field=models.JSONField(default=dict, help_text='Data sharing rules'),
        ),
        migrations.AlterField(
            model_name='study',
            name='comments',
            field=models.JSONField(default=dict, help_text='Comments'),
        ),
        migrations.AlterField(
            model_name='study',
            name='contacts',
            field=models.JSONField(default=dict, help_text='Study contacts'),
        ),
        migrations.AlterField(
            model_name='study',
            name='factors',
            field=models.JSONField(default=dict, help_text='Study factors'),
        ),
        migrations.AlterField(
            model_name='study',
            name='publications',
            field=models.JSONField(default=dict, help_text='Study publications'),
        ),
        migrations.AlterField(
            model_name='study',
            name='retraction_data',
            field=models.JSONField(default=dict, help_text='Consent retraction data'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sharing_data',
            field=models.JSONField(default=dict, help_text='Data sharing rules'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_design',
            field=models.JSONField(default=dict, help_text='Study design descriptors'),
        ),
    ]
