# Generated by Django 3.2.7 on 2021-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0018_isatab_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isatab',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='DateTime of ISAtab creation or restoring'),
        ),
    ]
