# Generated by Django 3.2.19 on 2023-06-13 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samplesheets', '0019_alter_isatab_date_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='irodsaccessticket',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='irodsaccessticket',
            name='project',
        ),
        migrations.AlterField(
            model_name='irodsaccessticket',
            name='assay',
            field=models.ForeignKey(blank=True, help_text='Assay in which the ticket belongs (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irods_access_tickets', to='samplesheets.assay'),
        ),
        migrations.AlterField(
            model_name='irodsaccessticket',
            name='date_expires',
            field=models.DateTimeField(blank=True, help_text='DateTime of ticket expiration (leave unset to never expire)', null=True),
        ),
        migrations.AlterField(
            model_name='irodsaccessticket',
            name='study',
            field=models.ForeignKey(help_text='Study in which the ticket belongs', on_delete=django.db.models.deletion.CASCADE, related_name='irods_access_tickets', to='samplesheets.study'),
        ),
        migrations.AlterField(
            model_name='irodsaccessticket',
            name='user',
            field=models.ForeignKey(help_text='User that created the ticket', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irods_access_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
