# Generated by Django 3.2.19 on 2023-07-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0028_populate_finder_role'),
        ('samplesheets', '0020_update_irodsaccessticket'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='irodsaccessticket',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='irodsdatarequest',
            name='action',
            field=models.CharField(default='DELETE', help_text='Action to be performed', max_length=64),
        ),
        migrations.AlterField(
            model_name='irodsdatarequest',
            name='description',
            field=models.CharField(blank=True, help_text='Request description (optional)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='irodsdatarequest',
            name='project',
            field=models.ForeignKey(help_text='Project to which the iRODS data request belongs', on_delete=django.db.models.deletion.CASCADE, related_name='irods_data_request', to='projectroles.project'),
        ),
        migrations.AlterField(
            model_name='irodsdatarequest',
            name='status',
            field=models.CharField(default='ACTIVE', help_text='Status of the request', max_length=16),
        ),
    ]
