# Generated by Django 3.2.22 on 2023-10-06 13:12
# NOTE: This updates the default IGV genome "b37" to "b37_1kg"
# NOTE: New versions of IGV no longer support "b37"

from django.db import migrations


APP_NAME = 'samplesheets'
OLD_GENOME = 'b37'
NEW_GENOME = 'b37_1kg'


def update_igv_genome(apps, old_id, new_id):
    """Update settings in database"""
    AppSetting = apps.get_model('projectroles', 'AppSetting')
    for s in AppSetting.objects.filter(
        app_plugin__name='samplesheets', name='igv_genome', value=old_id
    ):
        s.value = new_id
        s.save()


def run(apps, schema_editor):
    """Run update to change removed b37 IGV genome in existing settings"""
    update_igv_genome(apps, OLD_GENOME, NEW_GENOME)


def reverse(apps, schema_editor):
    """Reverse b37 IGV genome update in existing settings"""
    update_igv_genome(apps, NEW_GENOME, OLD_GENOME)


class Migration(migrations.Migration):

    dependencies = [
        ('samplesheets', '0021_update_irodsdatarequest'),
    ]

    operations = [
        migrations.RunPython(run, reverse_code=reverse)
    ]
