# Generated by Django 4.2.20 on 2025-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samplesheets", "0001_squashed_0023_alter_process_performer"),
    ]

    operations = [
        migrations.AddField(
            model_name="irodsaccessticket",
            name="allowed_hosts",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of allowed hosts (optional)",
                null=True,
            ),
        ),
    ]
