# Generated by Django 4.2.20 on 2025-04-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samplesheets", "0024_irodsaccessticket_allowed_hosts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irodsaccessticket",
            name="path",
            field=models.CharField(
                help_text="Path to iRODS collection or data object", max_length=255
            ),
        ),
    ]
